import mongoose from 'mongoose';

// ─── Schema ───────────────────────────────────────────────────────────────────
//
// CourierCODRemittance tracks the transfer of COD cash from any third-party
// courier (Shiprocket, Delhivery, Porter, etc.) back to the platform.
//
// When a customer pays via COD and the shipment is handled by a courier:
//   Customer → pays courier at delivery
//   Courier  → collects cash
//   Courier  → remits cash to platform (periodic bank transfer)
//   Admin    → confirms remittance receipt here
//   System   → COD escrow gate clears → vendor escrow can now release
//
// This is the HARD GATE that prevents vendor escrow release until the
// platform has actually received the COD money.
//
// For Own Fleet COD: CashSettlement is used instead (driver hands cash to admin).
//
// ──────────────────────────────────────────────────────────────────────────────

const courierCODRemittanceSchema = new mongoose.Schema(
    {
        // Identity
        remittanceNumber: {
            type:   String,
            unique: true,
            index:  true,
            // e.g., REM-2026-000001 — generated by pre-save hook
        },

        // Which courier provider this remittance is from
        providerId: {
            type:     String,
            required: true,
            index:    true,
            // 'shiprocket' | 'delhivery' | 'porter' | ...
            // No enum — open to any provider
        },

        // Provider's own reference (batch ID, UTR from their dashboard, etc.)
        providerReference: { type: String },

        // Links to the affected documents
        shipmentId: {
            type:     mongoose.Schema.Types.ObjectId,
            ref:      'Shipment',
            required: true,
            index:    true,
        },
        orderId: {
            type:     mongoose.Schema.Types.ObjectId,
            ref:      'Order',
            required: true,
            index:    true,
        },
        vendorId: {
            type:     mongoose.Schema.Types.ObjectId,
            ref:      'Vendor',
            required: true,
            index:    true,
        },
        awbCode: { type: String },

        // ─── Amounts ─────────────────────────────────────────────────────
        codAmountExpected: {
            type:     Number,
            required: true,
            min:      0,
        }, // The COD order total — what the courier should remit
        codAmountReceived: {
            type:    Number,
            default: null,
            min:     0,
        }, // Actual amount received (may differ due to courier deductions)
        variance: {
            type:    Number,
            default: null,
        }, // codAmountReceived - codAmountExpected (negative = platform shortfall)

        // ─── Status ──────────────────────────────────────────────────────
        remittanceStatus: {
            type:    String,
            enum:    ['pending', 'received', 'partial', 'disputed'],
            default: 'pending',
            index:   true,
        },

        // ─── Confirmation ─────────────────────────────────────────────────
        remittanceDate: { type: Date },    // date funds were transferred by courier
        confirmedBy:    { type: mongoose.Schema.Types.ObjectId, ref: 'Admin' },
        confirmedAt:    { type: Date },
        bankReference:  { type: String },  // UTR number or bank transfer reference

        notes: { type: String, trim: true },
    },
    { timestamps: true }
);

// ─── Indexes ─────────────────────────────────────────────────────────────────

courierCODRemittanceSchema.index({ remittanceStatus: 1, providerId: 1 });
// shipmentId: index:true already declared on field definition — no duplicate needed

// ─── Pre-save: Compute variance when amounts are set ─────────────────────────

courierCODRemittanceSchema.pre('save', function (next) {
    if (
        this.isModified('codAmountReceived') &&
        this.codAmountReceived !== null &&
        this.codAmountExpected !== null
    ) {
        this.variance = parseFloat(
            (this.codAmountReceived - this.codAmountExpected).toFixed(2)
        );
    }
    next();
});

// ─── Pre-save: Generate remittanceNumber ─────────────────────────────────────

courierCODRemittanceSchema.pre('save', async function (next) {
    if (this.isNew && !this.remittanceNumber) {
        const year  = new Date().getFullYear();
        const count = await mongoose.model('CourierCODRemittance').countDocuments();
        const seq   = String(count + 1).padStart(6, '0');
        this.remittanceNumber = `REM-${year}-${seq}`;
    }
    next();
});

const CourierCODRemittance = mongoose.model('CourierCODRemittance', courierCODRemittanceSchema);
export default CourierCODRemittance;
export { CourierCODRemittance };
