import mongoose from 'mongoose';

// ─── Sub-schemas ─────────────────────────────────────────────────────────────

const locationSchema = new mongoose.Schema(
    {
        pincode: { type: String },
        city:    { type: String },
        state:   { type: String },
    },
    { _id: false }
);

const packageDimensionsSchema = new mongoose.Schema(
    {
        length:  { type: Number },
        breadth: { type: Number },
        height:  { type: Number },
    },
    { _id: false }
);

const quoteEntrySchema = new mongoose.Schema(
    {
        providerId:       { type: String, required: true },
        providerName:     { type: String },

        // Financial
        customerCharge:   { type: Number }, // what customer would pay if this provider is chosen
        estimatedCost:    { type: Number }, // platform's delivery cost estimate for this provider
        margin:           { type: Number }, // customerCharge - estimatedCost

        // Performance
        etaHours:         { type: Number },
        etaDate:          { type: Date },

        // Scoring
        reliabilityScore: { type: Number }, // 0–100, from LogisticsProvider config at time of run
        selectionScore:   { type: Number }, // computed by engine scoring formula

        // Decision
        selectionStatus: {
            type: String,
            enum: ['SELECTED', 'REJECTED', 'UNAVAILABLE', 'API_TIMEOUT', 'NOT_EVALUATED'],
            required: true,
        },
        // Rejection/unavailability reason codes for analytics:
        // 'NO_DRIVER_AVAILABLE' | 'PINCODE_NOT_SERVICEABLE' | 'CAPABILITY_MISMATCH'
        // | 'LOWER_SCORE' | 'API_TIMEOUT' | 'PROVIDER_DISABLED' | 'WEIGHT_EXCEEDED'
        // | 'COD_NOT_SUPPORTED' | 'WAREHOUSE_ADDRESS_MISSING'
        rejectionReason:  { type: String },

        // Diagnostics
        apiResponseMs:    { type: Number }, // latency of provider's rate API call
        rawResponse:      { type: mongoose.Schema.Types.Mixed }, // snapshot for debugging
    },
    { _id: false }
);

// ─── Main Schema ─────────────────────────────────────────────────────────────

const deliveryEngineRunSchema = new mongoose.Schema(
    {
        // Identity
        runId: {
            type:   String,
            unique: true,
            index:  true,
            // e.g., DER-2026-000001 — generated by pre-save hook
        },

        // Set after order/shipment creation
        shipmentId: {
            type:  mongoose.Schema.Types.ObjectId,
            ref:   'Shipment',
            // Note: indexed via schema.index() below (avoids duplicate warning)
        },
        orderId: {
            type:  mongoose.Schema.Types.ObjectId,
            ref:   'Order',
            index: true,
        },
        vendorId: {
            type:  mongoose.Schema.Types.ObjectId,
            ref:   'Vendor',
            index: true,
        },

        // Run timing
        runTriggeredAt: { type: Date, required: true, default: Date.now },
        runCompletedAt: { type: Date },
        runDurationMs:  { type: Number },

        // Context at time of run
        origin:      { type: locationSchema },
        destination: { type: locationSchema },
        packageWeight:     { type: Number }, // grams
        packageDimensions: { type: packageDimensionsSchema },
        paymentMethod:     { type: String, enum: ['cod', 'online', 'wallet'] },

        // All provider quotes — SELECTED and REJECTED both stored
        quotes: { type: [quoteEntrySchema], default: [] },

        // Decision result
        selectedProviderId: { type: String },
        selectedBy: {
            type:    String,
            enum:    ['AUTO', 'ADMIN', 'MANUAL_OVERRIDE'],
            default: 'AUTO',
        },

        // Human-readable summary of the decision (auto-generated by engine)
        // Example: "Shiprocket SELECTED (Score: 87.4). Own Fleet REJECTED: No drivers available."
        selectionNotes: { type: String },
    },
    { timestamps: true }
);

// ─── Indexes ─────────────────────────────────────────────────────────────────

deliveryEngineRunSchema.index({ shipmentId: 1 }); // dedicated shipment lookup
deliveryEngineRunSchema.index({ orderId: 1, vendorId: 1 });
deliveryEngineRunSchema.index({ runTriggeredAt: -1 });
deliveryEngineRunSchema.index({ selectedProviderId: 1 });

// ─── Pre-save: Generate runId ─────────────────────────────────────────────────
// Uses timestamp + random suffix (not countDocuments) to avoid duplicate key errors
// when multiple engine runs are persisted concurrently in the same process.

deliveryEngineRunSchema.pre('save', function (next) {
    if (this.isNew && !this.runId) {
        const year   = new Date().getFullYear();
        const ts     = Date.now().toString(36).toUpperCase();        // base-36 timestamp
        const rand   = Math.random().toString(36).slice(2, 6).toUpperCase(); // 4 random chars
        this.runId   = `DER-${year}-${ts}-${rand}`;
    }
    next();
});

const DeliveryEngineRun = mongoose.model('DeliveryEngineRun', deliveryEngineRunSchema);
export default DeliveryEngineRun;
export { DeliveryEngineRun };
