import mongoose from 'mongoose';

// ─── Schema ───────────────────────────────────────────────────────────────────
//
// ShippingQuote is the lightweight "token" passed from the checkout estimation
// response back to the order creation request. It prevents re-running the
// Delivery Engine for the same session.
//
// Full analytics data lives in DeliveryEngineRun. This model stores only the
// minimum needed to lock in the selected provider's quote at order creation.
//
// ──────────────────────────────────────────────────────────────────────────────

const shippingQuoteSchema = new mongoose.Schema(
    {
        // Identity
        quoteId: {
            type:   String,
            unique: true,
            index:  true,
            // e.g., QT-2026-000001 — generated by pre-save hook
        },

        // Link to the full engine run that produced this quote
        deliveryEngineRunId: {
            type: mongoose.Schema.Types.ObjectId,
            ref:  'DeliveryEngineRun',
        },

        // Security / Validation
        quoteScope: {
            type:     String,
            required: true,
            index:    true,
            // e.g. "user:12345" or "guest:email@test.com"
        },

        // Set after the quote is used to create an order
        orderId: {
            type:  mongoose.Schema.Types.ObjectId,
            ref:   'Order',
            index: true,
        },
        vendorId: {
            type:  mongoose.Schema.Types.ObjectId,
            ref:   'Vendor',
            index: true,
        },

        // The winning provider's details
        providerId: {
            type:     String,
            required: true,
        },
        customerCharge:  { type: Number, required: true, min: 0 }, // what customer pays
        estimatedCost:   { type: Number, required: true, min: 0 }, // platform's estimated cost
        etaDate:         { type: Date },

        // Validity window (quotes expire to prevent stale pricing being used)
        expiresAt: {
            type:     Date,
            required: true,
            // Note: TTL index declared via schema.index() below (expireAfterSeconds)
            default: () => new Date(Date.now() + 15 * 60 * 1000),
        },

        // State
        usedForOrder: { type: Boolean, default: false },
    },
    { timestamps: true }
);

// ─── Indexes ─────────────────────────────────────────────────────────────────

shippingQuoteSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 }); // TTL index — auto-delete expired quotes
shippingQuoteSchema.index({ vendorId: 1, usedForOrder: 1 });

// ─── Pre-save: Generate quoteId ───────────────────────────────────────────────

shippingQuoteSchema.pre('save', function (next) {
    if (this.isNew && !this.quoteId) {
        const year = new Date().getFullYear();
        const ts   = Date.now().toString(36).toUpperCase();
        const rand = Math.random().toString(36).slice(2, 6).toUpperCase();
        this.quoteId = `QT-${year}-${ts}-${rand}`;
    }
    next();
});

const ShippingQuote = mongoose.model('ShippingQuote', shippingQuoteSchema);
export default ShippingQuote;
export { ShippingQuote };
